[build]
buildCommand = "cd backend && python -m pip install -r requirements.txt"

[deploy]
startCommand = "cd backend && uvicorn app.main:app --host 0.0.0.0 --port $PORT"
watchPaths = ["backend/**/*.py", "backend/requirements.txt", "backend/pyproject.toml"]